### ISSUE TITLE
Knob aliases not saved with patch file 

### ISSUE THREAD

**Issue by gabriel-roth** [4ms/4ms-vcv#20]
I've given aliases to the various knobs. They persist in the VCV patch. But when I save an MM patch, the `alias_name` isn't saved in the patch, so it doesn't appear on the MM. 

VCV patch: https://www.dropbox.com/scl/fi/k8vpkd1l28bbwbdhyj5cv/Plats-Clouds-Plateau.vcv?rlkey=4wrzcbm5i9aaf5dv1sihik5wf&st=6erlp4qm&dl=0

MM patch: https://www.dropbox.com/scl/fi/05shqqhgqth2cfhr83j09/Plaits-Clouds-Plateau.yml?rlkey=1qqyescbx95d3ajy1mb3vdq0c&st=mz63jg2t&dl=0

I don't have this problem with other patches — knob aliases typically work fine.

**Comment by danngreen** [comment]
Thanks! I found the issue, it was a bug. Creating a knob alias and then closing VCV Rack and re-opening it, then saving the MetaModule patch would fail to save the aliases in the MM patch file. So that's why it works sometimes and not other times.

It's merged into main now, and will be in the v2.0.5 release.
